---
language: ruby

bundler_args: --without system_tests development

cache: bundler

before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v

sudo: false

script: 'SPEC_OPTS="--format documentation" bundle exec rake validate lint spec strings:generate reference'

matrix:
  fast_finish: true
  include:
  - rvm: 2.4.9
    env: PUPPET_GEM_VERSION="~> 5"
  - rvm: 2.5.7
    env: PUPPET_GEM_VERSION="~> 6"
  - rvm: 2.4.9
    sudo: required
    services: docker
    env: BEAKER_set="centos-6" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.7
    sudo: required
    services: docker
    env: BEAKER_set="centos-6" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.9
    sudo: required
    services: docker
    env: BEAKER_set="centos-7" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.7
    sudo: required
    services: docker
    env: BEAKER_set="centos-7" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.9
    sudo: required
    services: docker
    env: BEAKER_set="centos-8" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.7
    sudo: required
    services: docker
    env: BEAKER_set="centos-8" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.9
    sudo: required
    services: docker
    env: BEAKER_set="debian-8" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.7
    sudo: required
    services: docker
    env: BEAKER_set="debian-8" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.9
    sudo: required
    services: docker
    env: BEAKER_set="debian-9" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.7
    sudo: required
    services: docker
    env: BEAKER_set="debian-9" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.9
    sudo: required
    services: docker
    env: BEAKER_set="debian-10" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.3
    sudo: required
    services: docker
    env: BEAKER_set="debian-10" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.9
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1404" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.7
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1404" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.9
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1604" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.7
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1604" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.9
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1804" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.7
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1804" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  allow_failures:
  # waiting for centos 8 release
  - rvm: 2.4.9
    env: BEAKER_set="centos-8" BEAKER_PUPPET_COLLECTION=puppet5
  - rvm: 2.5.7
    env: BEAKER_set="centos-8" BEAKER_PUPPET_COLLECTION=puppet6

notifications:
  email: false
