---
language: ruby

cache: bundler

before_install:
  - if [ $BUNDLER_VERSION ]; then
      gem install -v $BUNDLER_VERSION bundler --no-rdoc --no-ri;
    fi
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v

script: 'SPEC_OPTS="--format documentation" bundle exec rake validate lint spec'

matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: RUBYGEMS_VERSION=2.0.17 BUNDLER_VERSION=1.17.3 PUPPET_GEM_VERSION="~> 3.7.0"
  - rvm: 1.9.3
    env: RUBYGEMS_VERSION=2.0.17 BUNDLER_VERSION=1.17.3 PUPPET_GEM_VERSION="~> 3"
  - rvm: 1.9.3
    env: RUBYGEMS_VERSION=2.0.17 BUNDLER_VERSION=1.17.3 PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"
  - rvm: 2.0.0
    env: RUBYGEMS_VERSION=2.0.17 BUNDLER_VERSION=1.17.3 PUPPET_GEM_VERSION="~> 3.7.0"
  - rvm: 2.0.0
    env: RUBYGEMS_VERSION=2.0.17 BUNDLER_VERSION=1.17.3 PUPPET_GEM_VERSION="~> 3"
  - rvm: 2.0.0
    env: RUBYGEMS_VERSION=2.0.17 BUNDLER_VERSION=1.17.3 PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"
  - rvm: 2.1.9
    env: RUBYGEMS_VERSION=2.0.17 BUNDLER_VERSION=1.17.3 PUPPET_GEM_VERSION="~> 3.7.0"
  - rvm: 2.1.9
    env: RUBYGEMS_VERSION=2.0.17 BUNDLER_VERSION=1.17.3 PUPPET_GEM_VERSION="~> 3"
  - rvm: 2.1.9
    env: RUBYGEMS_VERSION=2.0.17 BUNDLER_VERSION=1.17.3 PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes"
  - rvm: 2.1.9
    env: RUBYGEMS_VERSION=2.7.8  BUNDLER_VERSION=1.17.3 PUPPET_GEM_VERSION="~> 4"
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5"
  - rvm: 2.5.1
    env: PUPPET_GEM_VERSION="~> 6"

notifications:
  email: false
