---
env:
- PUPPET_VERSION=2.6.9
- PUPPET_VERSION=2.7.13
- PUPPET_VERSION=3.2.1
notifications:
email: false
global:
- PUBLISHER_LOGIN=ghoneycutt
- secure: |-
    fSNt35EMHQ0nqBnvut1DP5jOqzYHLCUq83miWD//qShKwfCaeRREcl22uZBQ
    AqNPtoR7qW1dGZgFQjnEiY6Cx969S0imGswdAoIgbblkiyJHvqNHAidRSUGG
    wsb82BNaH4XAk09v5HYiAYOkOEj8LidFZMLe683s1XFeVT1pcMo=
rvm:
- 1.9.3
- 1.8.7
matrix:
  allow_failures:
  - env: PUPPET_VERSION=2.6.9
language: ruby
before_script: gem install --no-ri --no-rdoc bundler
script:
- rake spec
gemfile: .gemfile
